
[types]

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.forcecraft]
			force = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.forbidden_arcanus]
			cherry = true
			aurum = true
			nuggety_aurum = true

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.forcecraft]
			force = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.valhelsia_structures]
			lapidified_jungle = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			cherry = true
			aurum = true
			edelwood = true

	[types.cut_block_type]

		[types.cut_block_type.forcecraft]
			force_plank = true
			force_brick_red = true
			force_brick_yellow = true
			force_brick_green = true
			force_brick_blue = true
			force_brick_white = true
			force_brick_black = true
			force_brick_brown = true
			force_brick_orange = true
			force_brick_light_blue = true
			force_brick_magenta = true
			force_brick_pink = true
			force_brick_light_gray = true
			force_brick_lime = true
			force_brick_cyan = true
			force_brick_purple = true
			force_brick_gray = true
			force_brick = true

		[types.cut_block_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.cut_block_type.botania]
			corporea_brick = true
			livingwood = true
			stripped_livingwood = true
			livingwood_planks = true
			livingrock = true
			polished_livingrock = true
			livingrock_bricks = true
			mossy_livingrock_bricks = true
			dreamwood = true
			stripped_dreamwood = true
			dreamwood_planks = true
			dark_quartz = true
			mana_quartz = true
			blaze_quartz = true
			lavender_quartz = true
			red_quartz = true
			elf_quartz = true
			sunny_quartz = true
			white_pavement = true
			black_pavement = true
			blue_pavement = true
			yellow_pavement = true
			red_pavement = true
			green_pavement = true
			metamorphic_forest_stone = true
			metamorphic_forest_cobblestone = true
			metamorphic_forest_bricks = true
			metamorphic_plains_stone = true
			metamorphic_plains_cobblestone = true
			metamorphic_plains_bricks = true
			metamorphic_mountain_stone = true
			metamorphic_mountain_cobblestone = true
			metamorphic_mountain_bricks = true
			metamorphic_fungal_stone = true
			metamorphic_fungal_cobblestone = true
			metamorphic_fungal_bricks = true
			metamorphic_swamp_stone = true
			metamorphic_swamp_cobblestone = true
			metamorphic_swamp_bricks = true
			metamorphic_desert_stone = true
			metamorphic_desert_cobblestone = true
			metamorphic_desert_bricks = true
			metamorphic_taiga_stone = true
			metamorphic_taiga_cobblestone = true
			metamorphic_taiga_bricks = true
			metamorphic_mesa_stone = true
			metamorphic_mesa_cobblestone = true
			metamorphic_mesa_bricks = true
			shimmerrock = true
			shimmerwood_planks = true

		[types.cut_block_type.tombstone]
			dark_marble = true
			white_marble = true
			blue_marble = true
			green_marble = true
			carmin_marble = true

		[types.cut_block_type.pneumaticcraft]
			reinforced_brick = true
			reinforced_stone = true
			compressed_brick = true
			compressed_stone = true

		[types.cut_block_type.ars_nouveau]
			archwood = true
			sourcestone = true
			sourcestone_mosaic = true
			sourcestone_basketweave = true
			sourcestone_alternating = true
			sourcestone_large_bricks = true
			sourcestone_small_bricks = true
			smooth_sourcestone_basketweave = true
			smooth_sourcestone_mosaic = true
			smooth_sourcestone_alternating = true
			smooth_sourcestone_large_bricks = true
			smooth_sourcestone = true
			smooth_sourcestone_small_bricks = true
			gilded_sourcestone_mosaic = true
			gilded_sourcestone_basketweave = true
			gilded_sourcestone_alternating = true
			gilded_sourcestone_large_bricks = true
			gilded_sourcestone_small_bricks = true
			smooth_gilded_sourcestone_mosaic = true
			smooth_gilded_sourcestone_basketweave = true
			smooth_gilded_sourcestone_alternating = true
			smooth_gilded_sourcestone_large_bricks = true
			smooth_gilded_sourcestone_small_bricks = true

		[types.cut_block_type.thermal]
			rubberwood = true

		[types.cut_block_type.biomesoplenty]
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			orange_sandstone = true
			smooth_orange_sandstone = true
			cut_orange_sandstone = true
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.cut_block_type.immersiveengineering]
			sheetmetal_copper = true
			sheetmetal_aluminum = true
			storage_aluminum = true
			sheetmetal_lead = true
			storage_lead = true
			sheetmetal_silver = true
			storage_silver = true
			sheetmetal_nickel = true
			storage_nickel = true
			sheetmetal_uranium = true
			storage_uranium = true
			sheetmetal_constantan = true
			storage_constantan = true
			sheetmetal_electrum = true
			storage_electrum = true
			sheetmetal_steel = true
			storage_steel = true
			sheetmetal_iron = true
			sheetmetal_gold = true
			treated_wood_horizontal = true
			treated_wood_vertical = true
			treated_wood_packaged = true
			sheetmetal_colored_white = true
			sheetmetal_colored_orange = true
			sheetmetal_colored_magenta = true
			sheetmetal_colored_light_blue = true
			sheetmetal_colored_yellow = true
			sheetmetal_colored_lime = true
			sheetmetal_colored_pink = true
			sheetmetal_colored_gray = true
			sheetmetal_colored_light_gray = true
			sheetmetal_colored_cyan = true
			sheetmetal_colored_purple = true
			sheetmetal_colored_blue = true
			sheetmetal_colored_brown = true
			sheetmetal_colored_green = true
			sheetmetal_colored_red = true
			sheetmetal_colored_black = true
			steel_scaffolding_standard = true
			alu_scaffolding_standard = true
			steel_scaffolding_grate_top = true
			alu_scaffolding_grate_top = true
			steel_scaffolding_wooden_top = true
			alu_scaffolding_wooden_top = true
			cokebrick = true
			blastbrick = true
			blastbrick_reinforced = true
			coke = true
			hempcrete = true
			hempcrete_brick = true
			concrete = true
			concrete_brick = true
			concrete_tile = true
			concrete_leaded = true
			insulating_glass = true
			alloybrick = true

		[types.cut_block_type.create]
			copper_shingle = true
			exposed_copper_shingle = true
			weathered_copper_shingle = true
			oxidized_copper_shingle = true
			waxed_copper_shingle = true
			waxed_exposed_copper_shingle = true
			waxed_weathered_copper_shingle = true
			waxed_oxidized_copper_shingle = true
			copper_tile = true
			exposed_copper_tile = true
			weathered_copper_tile = true
			oxidized_copper_tile = true
			waxed_copper_tile = true
			waxed_exposed_copper_tile = true
			waxed_weathered_copper_tile = true
			waxed_oxidized_copper_tile = true
			cut_granite = true
			polished_cut_granite = true
			cut_granite_brick = true
			small_granite_brick = true
			cut_diorite = true
			polished_cut_diorite = true
			cut_diorite_brick = true
			small_diorite_brick = true
			cut_andesite = true
			polished_cut_andesite = true
			cut_andesite_brick = true
			small_andesite_brick = true
			cut_calcite = true
			polished_cut_calcite = true
			cut_calcite_brick = true
			small_calcite_brick = true
			cut_dripstone = true
			polished_cut_dripstone = true
			cut_dripstone_brick = true
			small_dripstone_brick = true
			cut_deepslate = true
			polished_cut_deepslate = true
			cut_deepslate_brick = true
			small_deepslate_brick = true
			cut_tuff = true
			polished_cut_tuff = true
			cut_tuff_brick = true
			small_tuff_brick = true
			cut_asurine = true
			polished_cut_asurine = true
			cut_asurine_brick = true
			small_asurine_brick = true
			cut_crimsite = true
			polished_cut_crimsite = true
			cut_crimsite_brick = true
			small_crimsite_brick = true
			cut_limestone = true
			polished_cut_limestone = true
			cut_limestone_brick = true
			small_limestone_brick = true
			cut_ochrum = true
			polished_cut_ochrum = true
			cut_ochrum_brick = true
			small_ochrum_brick = true
			cut_scoria = true
			polished_cut_scoria = true
			cut_scoria_brick = true
			small_scoria_brick = true
			cut_scorchia = true
			polished_cut_scorchia = true
			cut_scorchia_brick = true
			small_scorchia_brick = true
			cut_veridium = true
			polished_cut_veridium = true
			cut_veridium_brick = true
			small_veridium_brick = true

		[types.cut_block_type.ae2]
			sky_stone_brick = true
			sky_stone_small_brick = true
			smooth_quartz = true
			quartz_brick = true
			quartz_pillar = true

		[types.cut_block_type.mekanismadditions]
			black_plastic = true
			black_plastic_glow = true
			black_plastic_transparent = true
			blue_plastic = true
			blue_plastic_glow = true
			blue_plastic_transparent = true
			green_plastic = true
			green_plastic_glow = true
			green_plastic_transparent = true
			cyan_plastic = true
			cyan_plastic_glow = true
			cyan_plastic_transparent = true
			dark_red_plastic = true
			dark_red_plastic_glow = true
			dark_red_plastic_transparent = true
			purple_plastic = true
			purple_plastic_glow = true
			purple_plastic_transparent = true
			orange_plastic = true
			orange_plastic_glow = true
			orange_plastic_transparent = true
			light_gray_plastic = true
			light_gray_plastic_glow = true
			light_gray_plastic_transparent = true
			gray_plastic = true
			gray_plastic_glow = true
			gray_plastic_transparent = true
			light_blue_plastic = true
			light_blue_plastic_glow = true
			light_blue_plastic_transparent = true
			lime_plastic = true
			lime_plastic_glow = true
			lime_plastic_transparent = true
			aqua_plastic = true
			aqua_plastic_glow = true
			aqua_plastic_transparent = true
			red_plastic = true
			red_plastic_glow = true
			red_plastic_transparent = true
			magenta_plastic = true
			magenta_plastic_glow = true
			magenta_plastic_transparent = true
			yellow_plastic = true
			yellow_plastic_glow = true
			yellow_plastic_transparent = true
			white_plastic = true
			white_plastic_glow = true
			white_plastic_transparent = true
			brown_plastic = true
			brown_plastic_glow = true
			brown_plastic_transparent = true
			pink_plastic = true
			pink_plastic_glow = true
			pink_plastic_transparent = true

		[types.cut_block_type.quark]
			bamboo_planks = true
			duskbound_block = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			midori_block = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			iron_plate = true
			rusty_iron_plate = true
			permafrost = true
			permafrost_bricks = true
			ancient_planks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			blossom_planks = true
			azalea_planks = true

		[types.cut_block_type.supplementaries]
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.valhelsia_structures]
			lapidified_jungle = true

		[types.cut_block_type.forbidden_arcanus]
			darkstone = true
			polished_darkstone = true
			polished_darkstone_brick = true
			arcane_polished_darkstone = true
			soulless_sandstone = true
			cut_soulless_sandstone = true
			polished_soulless_sandstone = true
			fungyss = true
			cherry = true
			aurum = true
			edelwood = true

		[types.cut_block_type.ad_astra]
			iron_plating = true
			steel_plating = true
			desh_plating = true
			ostrum_plating = true
			calorite_plating = true
			moon_stone = true
			moon_cobblestone = true
			moon_stone_brick = true
			polished_moon_stone = true
			aeronos = true
			strophar = true
			mars_stone = true
			mars_cobblestone = true
			mars_stone_brick = true
			polished_mars_stone = true
			mercury_stone = true
			mercury_cobblestone = true
			mercury_stone_brick = true
			polished_mercury_stone = true
			venus_stone = true
			venus_cobblestone = true
			venus_stone_brick = true
			polished_venus_stone = true
			venus_sandstone_brick = true
			glacio_stone = true
			glacio_cobblestone = true
			glacio_stone_brick = true
			polished_glacio_stone = true
			permafrost_brick = true
			chiseled_permafrost_brick = true
			polished_permafrost = true
			glacian = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.valhelsia_structures]
			stripped_post = true
			cut_post = true
			post = true
			cut_stripped_post = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

